blablacar/dgr

utils/packer.go

to be able to use php5-curl or curl in container that needs it

Remove Curl from cleanup 

---

README.md
builder/cnt.go
commands/cnt.go
commands/init.go

Some Stuff might not be pretty , I'm not fan of the hack to bypass the cnt-manifest.yml for example
But it works ^^

Init Function

---

builder/cnt.go

Fix Missing Slash + notInit

---

builder/cnt.go

Some Forard slash were still missing ...
My bad for the bad tree

Final fix -.-

---

builder/aci-build.go
builder/aci.go
commands/cnt.go

F ix build prestart

---

builder/aci-build.go
builder/aci-init.go
builder/build.go
commands/init.go

Issue : https://github.com/blablacar/cnt/issues/25

cnt init -p /my/path

---

commands/init.go
utils/tar.go

Keep permission on tar --- cnt init without -p

---

builder/aci-init.go

A bit dirty but it works

---

builder/aci-update.go
commands/cnt.go
commands/update.go

We could change the name of the function to have something more explicit.

Update conf without full reinstall

---

commands/cnt.go

fix systemd-nspawn target directory

---

builder/aci.go

fix 2, Missing /*

---

utils/image-manifest.go

rkt labels OS/ARCH https://github.com/coreos/rkt/pull/1493

---

builder/aci-build.go

Build without share system

---

README.md

- Fix punctuations & typos (eg. no space before :)
- Use shield badges to uniformize layout
- Fix markdown formatting

Small fixes on readme

---

examples/build.sh
examples/centos/aci-centos/aci-manifest.yml
examples/centos/aci-centos/attributes/yum.yml
examples/centos/aci-centos/runlevels/builder/install.sh
examples/centos/aci-centos/runlevels/inherit-build-early/00.env-to-attributes.sh
examples/centos/aci-centos/runlevels/inherit-build-early/01.yum-update.sh
examples/centos/aci-centos/templates/etc/yum/yum.conf.tmpl

In examples.
aci-centos builder.

[Demo] aci-centos

---

bin-templater/template/templating.go
bin-templater/tests/1/templates/etc/test.tmpl
bin-templater/tests/1/templates/test.partial

Some change will probably have to be reverted in the template
And the code probably need a little cleanup

Templater fn

---

bin-templater/template/templating.go
bin-templater/tests/6/attributes/resolv.conf.yml
bin-templater/tests/6/templates/dns.partial
bin-templater/tests/6/templates/etc/resolv.conf.tmpl
bin-templater/tests/templater.bats

Purpose is to provide several variables to templates:
{{template "userlist" dict "Users" .MostPopular "Current" .CurrentUser}}

Introduce dict template func

---

dgr/aci-test.go

Use --net=default in dgr test

---

README.md

Adds installation instructions.

---

index.html

Can't test wether it breaks discovery or not, but at least HTML validation won't break on it any more :)

Move ac-discovery meta inside head block.

---

dgr/aci-update.go
dgr/command.go
dgr/main.go
dgr/pod-build.go
examples/debian/aci-debian/runlevels/builder/10.debootstrap.sh

[Experimental] - Implement dgr update.

---

dgr/aci-test.go
examples/alpine/aci-alpine-base/runlevels/builder/10.build.sh

Check if isolators are set on tester, fallback on tested aci ones if absent

Feat isolators on tester

---

aci-builder/files/dgr/builder/stage2/builder.sh

ld_preload systemd-nspawn in stage2 prepare
